import {ITableData} from "../types"

export const mockData: ITableData = {
    type: 'referrals',
    thead: [
        {
            id: 1,
            name: 'referral event',
            key: 'event',
            width: '250px',
        },
        {
            id: 2,
            name: 'advocate',
            key: 'advocate',
            width: '250px',
        },
        {
            id: 3,
            name: 'friend',
            key: 'friend',
            width: '250px',
        },
        {
            id: 4,
            name: 'referral status',
            key: 'status',
            width: '250px',
        },
    ],
    tbody: [
        {
            id: 1,
            name: 'purchase',
            date: '03/12/2022 at 7.12 PM PDT',
            total: '$110.00',
            advocate_mail: 'asad213123123@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'zxczxc@zxc.com',
            friend: 'Friend',
            status: 'pending',
            status_massage: 'passed fraud checks',
        },
        {
            id: 2,
            name: 'purchase',
            date: '01/12/2022 at 7.12 PM PDT',
            total: '$120.00',
            advocate_mail: 'asad323@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'asad213123123@asdasdasd.com',
            friend: 'Friend',
            status: 'flagged',
            status_massage: 'marked as fraud',
        },
        {
            id: 3,
            name: 'purchase',
            date: '03/12/2022 at 7.12 PM PDT',
            total: '$130.00',
            advocate_mail: 'asad213123123@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'dgfgdfg@ytui.com',
            friend: 'Friend',
            status: 'approved',
            status_massage: 'passed fraud checks',
        },
        {
            id: 4,
            name: 'purchase',
            date: '01/12/2022 at 7.12 PM PDT',
            total: '$140.00',
            advocate_mail: 'rty3@rty.com',
            advocate: 'advocate',
            friend_mail: 'asad213123123@asdasdasd.com',
            friend: 'Friend',
            status: 'flagged',
            status_massage: 'marked as fraud',
        },
        {
            id: 5,
            name: 'purchase',
            date: '03/12/2022 at 7.12 PM PDT',
            total: '$110.00',
            advocate_mail: 'asad213123123@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'zxczxc@zxc.com',
            friend: 'Friend',
            status: 'pending',
            status_massage: 'passed fraud checks',
        },
        {
            id: 6,
            name: 'purchase',
            date: '01/12/2022 at 7.12 PM PDT',
            total: '$120.00',
            advocate_mail: 'asad323@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'asad213123123@asdasdasd.com',
            friend: 'Friend',
            status: 'flagged',
            status_massage: 'marked as fraud',
        },
        {
            id: 7,
            name: 'purchase',
            date: '03/12/2022 at 7.12 PM PDT',
            total: '$130.00',
            advocate_mail: 'asad213123123@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'dgfgdfg@ytui.com',
            friend: 'Friend',
            status: 'approved',
            status_massage: 'passed fraud checks',
        },
        {
            id: 8,
            name: 'purchase',
            date: '01/12/2022 at 7.12 PM PDT',
            total: '$140.00',
            advocate_mail: 'rty3@rty.com',
            advocate: 'advocate',
            friend_mail: 'asad213123123@asdasdasd.com',
            friend: 'Friend',
            status: 'flagged',
            status_massage: 'marked as fraud',
        },
        {
            id: 9,
            name: 'purchase',
            date: '03/12/2022 at 7.12 PM PDT',
            total: '$110.00',
            advocate_mail: 'asad213123123@asdasdasd.com',
            advocate: 'advocate',
            friend_mail: 'zxczxc@zxc.com',
            friend: 'Friend',
            status: 'pending',
            status_massage: 'passed fraud checks',
        }
    ]
}
